---
# Install the Zabbix server and its prerequisites

- name: Include Zabbix server specific variables
  include_vars:
    file: vars/zbx_server_vars.yml

- name: Install Zabbix server prerequisites (apache, php, mysql)
  become: true
  package:
    name: "{{ item }}"
    state: present
  vars:
    item:
    - apache2
    - libapache2-mod-php
    - mysql-server
    - php
    - php-mbstring
    - php-gd
    - php-xml
    - php-bcmath
    - php-ldap
    - php-mysql
# Required for database operations with Ansibles mysql-modules
    - python-pymysql

- name: Add Zabbix repository to apt sources
  become: true
  apt:
    deb: "https://repo.zabbix.com/zabbix/4.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.2-2+bionic_all.deb"

- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install Zabbix server
  become: true
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - zabbix-server-mysql
    - zabbix-frontend-php

# This is an unfortunate way to perform a root password change (saving the password in a plaintext
# .my.cnf), but other options have their drawbacks as well, and at least it's root-accessible only.
- name: Copy my.cnf to the zabbix server
  become: true
  template: src=templates/root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  become: yes
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_passwd }}"
    check_implicit_admin: yes
# This is needed to work around an issue with MySQL 5.7 and older Ansible versions
# More info here: https://github.com/ansible/ansible/issues/47736
    login_unix_socket: /var/run/mysqld/mysqld.sock
    priv: "*.*:ALL,GRANT"
  with_items:
    - "%"
    - 127.0.0.1
    - ::1
    - localhost

- name: Create a new database for zabbix
  become: true
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    name: zabbix
    encoding: utf8
    collation: utf8_bin
    state: present

- name: Create zabbix user with all privileges for zabbix database
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    name: zabbix
    password: "{{ mysql_zabbix_passwd }}"
    priv: 'zabbix.*:ALL'
    state: present

# This is another workaround we have to perform due to this bug
# which otherwise leads to pipe errors
# https://github.com/ansible/ansible/pull/26504
- name: Unpack initial zabbix db schema from .gz
  become: true
  shell: gunzip -k -f /usr/share/doc/zabbix-server-mysql/create.sql.gz

- name: Import initial db schema and data to zabbix database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_passwd }}"
    state: import
    name: zabbix
    target: /usr/share/doc/zabbix-server-mysql/create.sql

- name: Configure zabbix config for database access
  become: true
  replace:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^# DBPassword=$'
    replace: "DBPassword={{ mysql_zabbix_passwd }}"

- name: Configure PHP timezone correctly for zabbix
  become: true
  replace:
    path: /etc/apache2/conf-enabled/zabbix.conf
    regexp: '^        # php_value date.timezone Europe/Riga$'
    replace: "        php_value date.timezone Europe/Helsinki"

- name: Restart apache and zabbix-server
  become: true
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - apache2
    - zabbix-server